blueprint:
  name: "AWTRIX Finnish Flag Day Display"
  description: "Display todays Finnish Flag Day on the Ulanzi Clock on Awtrix firmware"
  domain: automation
  author: tikinaattori
  input:
    awtrix:
      name: Awtrix Ulanzi Clock
      description: "The Awtrix Ulanzi Clock entity"
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX 3
    sensor:
      name: Python script sensor
      description: "The sensor for Python script"
      selector:
        entity:
          domain: sensor
    flagday_color:
      name: flagday color
      description: "The color of the flagday text"
      selector:
        text:
      default: "00FF00"
    repeat:
      name: Repeat
      description: "The number of times the text is repeated"
      selector:
        text:
      default: 3
mode: restart
variables:
  device_id: !input awtrix
  awtrix_display: "{{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) | string }}"
  sensor: !input sensor
  flagday: '{{states(sensor) | string }}'
  flagday_index_text: !input flagday_index_text
  flagday_index_color: !input flagday_index_color
  flagday_color: !input flagday_color
  repeat: !input repeat
  payload: |-
    {
      "icon": "10076",
      "text": "{{ flagday | string}}",
      "repeat": {{ repeat }}
    }
trigger:
- platform: state
  entity_id: !input sensor
  id: Changes
  enabled: true
condition: []
action:
  - action: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_display }}/custom/flagday"
      payload: '{{ payload }}'