blueprint:
  name: "AWTRIX Linkki Next Bus"
  description: "Displays the minutes to the next bus on the Ulanzi Clock on Awtrix firmware"
  domain: automation
  author: tikinaattori
  input:
    awtrix:
      name: Awtrix Ulanzi Clock
      description: "The Awtrix Ulanzi Clock entity"
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX 3
    sensor:
      name: Bus stop sensor
      description: "The sensor for bus stop information using Digitransit HACS integration"
      selector:
        entity:
          domain: sensor
    repeat:
      name: Repeat
      description: How many times the message should be repeated
      selector:
        number:
          min: 0.0
          max: 30.0
          unit_of_measurement: times
          step: 1.0
          mode: slider
      default: 3
    icon:
      name: Icon
      description: "The icon to display"
      selector:
        text:
      default: "11999"  # Default icon for bus
    color:
      name: Color
      description: "The color of the text"
      selector:
        text:
      default: "005EB8"
    scroll_speed:
      name: Scroll Speed
      description: How fast the message should scroll
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: percent
          step: 10.0
          mode: slider
      default: 80
mode: restart
variables:
  device_id: !input awtrix
  sensor: !input sensor
  awtrix_display: "{{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) | string }}"
  text: "Seuraavaan bussiin aikaa {{ states(sensor) | string }} minuuttia. Tämän jälkeen seuraavat bussit: {% for departure in state_attr(sensor, 'departures')[1:] %} {{ departure.route }}: {{ as_datetime(departure.realtimeDeparture).strftime('%H:%M') }}{% endfor %}"
  repeat: !input repeat
  icon: !input icon
  color: !input color
  scroll_speed: !input scroll_speed
  payload: >-
      {
        "icon": "{{ icon | string }}",
        "text": "{{ text | string}}",
        "color": "{{ color | string }}",
        "repeat": {{ repeat | int }},
        "pushIcon": 2,
        "scrollSpeed": {{ scroll_speed | int }}
      }
trigger:
- platform: state
  entity_id: !input sensor
  id: Changes
  enabled: true
condition: []
action:
  - action: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_display }}/custom/nextbus"
      payload: '{{ payload }}'