blueprint:
  name: "AWTRIX Sunrise/Sunset Display"
  description: "Display todays Sunrise/Sunset time on the Ulanzi Clock on Awtrix firmware"
  domain: automation
  author: tikinaattori
  input:
    awtrix:
      name: Awtrix Ulanzi Clock
      description: "The Awtrix Ulanzi Clock entity"
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: false
    sunrise_sunset:
      name: Sunrise/Sunset
      description: Sunrise or Sunset automation
      selector:
        select:
          options:
            - "sunrise"
            - "sunset"
    sensor:
      name: Sunrise/Sunset
      description: "The sensor for the sunrise or sunset"
      selector:
        entity:
          domain: sensor
    icon:
      name: Icon
      description: "Icon of the sunset or sunrise"
      selector:
        text:
      default: "44904"
    message_duration:
      name: Message Duration
      description: How long the message should be displayed
      selector:
        number:
          min: 0.0
          max: 30.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
      default: 10
mode: restart
variables:
  device_id: !input awtrix
  awtrix_display: "{{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) | string }}"
  sunrise_sunset: !input sunrise_sunset
  sensor: !input sensor
  sunrise_sunset_time: '{{states(sensor) | string }}'
  icon: !input icon
  message_duration: !input repeat
  payload: |-
    {
      "icon": "{{ icon }}",
      "text": "{{ as_timestamp(sunrise_sunset_time) | timestamp_custom('%H:%M') }}"
      "duration": "{{ message_duration }}"
    }
trigger:
- platform: state
  entity_id: !input sensor
  id: Changes
  enabled: true
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_display }}/custom/{{ sunrise_sunset }}"
      payload: '{{ payload }}'