blueprint:
  name: "AWTRIX Weather Display"
  description: "Display todays weather on the Ulanzi Clock on Awtrix firmware"
  domain: automation
  author: tikinaattori
  input:
    awtrix:
      name: Awtrix Ulanzi Clock
      description: "The Awtrix Ulanzi Clock entity"
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: false
    weather_sensor:
      name: Weather Condition sensor
      description: "The weather condition sensor to use"
      selector:
        entity:
          filter:
            integration: accuweather, openweathermap
            domain: sensor
    weather_max_temp_entity:
      name: Max Temp. entity
      description: "The entity for the maximum temperature"
      selector:
        entity:
          domain: sensor
    weather_min_temp_entity:
      name: Min Temp. entity
      description: "The entity for the minimum temperature"
      selector:
        entity:
          domain: sensor
    repeat:
      name: Repeat
      description: How many times the message should be repeated
      selector:
        number:
          min: 0.0
          max: 30.0
          unit_of_measurement: times
          step: 1.0
          mode: slider
      default: 3
    scroll_speed:
      name: Scroll Speed
      description: How fast the message should scroll
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: percent
          step: 10.0
          mode: slider
      default: 80
    weather_unit:
      name: Weather unit
      description: "The unit of the temperature"
      selector:
        text:
      default: "°C"
mode: restart
variables:
  device_id: !input awtrix
  awtrix_display: "{{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name') ) | string }}"
  repeat: !input repeat
  weather_sensor: !input weather_sensor
  weather_condition: '{{states(weather_sensor) | string }}'
  weather_max_temp: !input weather_max_temp_entity
  weather_min_temp: !input weather_min_temp_entity
  weather_max: '{{states(weather_max_temp) | string }}'
  weather_min: '{{states(weather_min_temp) | string }}'
  weather_unit: !input weather_unit
  scroll_speed: !input scroll_speed
  payload: |-
    {
      "text": 'Weather today: {{ weather_condition }}, Max Temp.: {{ weather_max }} {{ weather_unit }}, Min Temp.: {{ weather_min }} {{ weather_unit }}',
      "repeat": {{repeat}},
      "scrollSpeed": {{ scroll_speed }}
    }
trigger:
- platform: state
  entity_id: !input weather_sensor
  id: Changes
  enabled: true
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_display }}/custom/weather"
      payload: '{{ payload }}'