blueprint:
  name: AWTRIX Weather Display
  description: Display todays weather on the Ulanzi Clock on Awtrix firmware
  domain: automation
  author: tikinaattori
  input:
    awtrix:
      name: Awtrix Ulanzi Clock
      description: The Awtrix Ulanzi Clock entity
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX 3
    weather_text:
      name: Weather text
      description: The text to display
      selector:
        text: {}
      default: "Weather today:"
    awtrix_custom_app_name:
      name: MQTT Topic Path
      description: The unique name of the custom app
      selector:
        text: {}
      default: weather
    weather_sensor:
      name: Weather Condition sensor
      description: The weather condition sensor to use
      selector:
        entity:
          include_entities:
            - weather.forecast_home
<<<<<<< HEAD
            - weather.openweathermap
=======
            - sensor.openweathermap_condition
            - sensor.openweathermap_forecast_condition
>>>>>>> 9dbf8e9 (update weather blueprint)
          multiple: false
    repeat:
      name: Repeat
      description: How many times the message should be repeated
      selector:
        number:
          min: 0.0
          max: 30.0
          unit_of_measurement: times
          step: 1.0
          mode: slider
      default: 3
    scroll_speed:
      name: Scroll Speed
      description: How fast the message should scroll
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: percent
          step: 10.0
          mode: slider
      default: 80
<<<<<<< HEAD
=======
    weather_unit:
      name: Weather unit
      description: The unit of the temperature
      selector:
        text: {}
      default: °C
>>>>>>> 9dbf8e9 (update weather blueprint)
  source_url: https://github.com/joonastikkanen/awtrix/blob/main/homeassistant_blueprints%2Fweather.yaml
mode: restart
variables:
  device_id: !input awtrix
  awtrix_display:
    "{{ iif( device_attr(device_id, 'name_by_user') != none, device_attr(device_id,
    'name_by_user'), device_attr(device_id, 'name') ) | string }}"
  awtrix_custom_app_name: !input awtrix_custom_app_name
  repeat: !input repeat
  weather_text: !input weather_text
  weather_sensor: !input weather_sensor
  weather_condition: "{{states(weather_sensor) | string }}"
<<<<<<< HEAD
  weather_temp: "{{ state_attr(weather_sensor, 'temperature')}}"
  weather_unit: "{{ state_attr(weather_sensor, 'temperature_unit')}}"
  scroll_speed: !input scroll_speed
  payload: "{\n  \"text\": '{{ weather_text }} {{ weather_condition }}, {{ weather_temp }} {{ weather_unit }}',\n  \"repeat\": {{repeat}},\n  \"scrollSpeed\": {{ scroll_speed }}\n}"
=======
  weather_unit: !input weather_unit
  scroll_speed: !input scroll_speed
  payload: "{\n  \"text\": '{{ weather_text }} {{ weather_condition }}',\n  \"repeat\": {{repeat}},\n  \"scrollSpeed\": {{ scroll_speed }}\n}"
>>>>>>> 9dbf8e9 (update weather blueprint)
triggers:
  - trigger: state
    entity_id: !input weather_sensor
    id: Changes
    enabled: true
condition: []
actions:
  - action: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_display }}/custom/{{ awtrix_custom_app_name }}"
      payload: "{{ payload }}"
